on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]

jobs:
  my_job:
    runs-on: macos-latest
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.issue.pull_request && contains( github.event.comment.body, 'my-special-message' )) }}
    steps:
    
      - name: Extracting PR route
        if: ${{ github.event.issue.pull_request }}
        id: extracting_route
        run: |
          echo "::set-output name=route::$(echo ${{ github.event.issue.pull_request.url }}  | sed s-https://api.github.com--)"
          
      - name: Getting PR data
        if: ${{ github.event.issue.pull_request }}
        id: pr_data
        uses: octokit/request-action@v2.x
        with:
          route: GET ${{ steps.extracting_route.outputs.route }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Checkout PRed branch
        uses: actions/checkout@v2
        if: ${{ github.event.issue.pull_request }}
        with:
          ref: ${{ fromJson(steps.pr_data.outputs.data).head.ref }}
