name: pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name tss
        if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
        id: check
        with:
          trigger: '@deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: |
         echo say hello
        if: steps.check.outputs.triggered == 'true'


